### ISSUE TITLE
Is Automatic Compositional Testing not Supported?

### ISSUE THREAD

**Issue by 2over12** [GillianPlatform/Gillian#114]
Hi, I was attempting to mess around with ACT on some of the gillian-c examples and a simplified example. wpst and verify work fine for me, but every example I've run (in `Gillian-C/examples/act`)  act on thus far fails UP.init_prog with `Unification plan creation failure.` and `Missing assertions: x`. I noticed that ACT is commented out in the test scripts. Honestly, not clear to me what the unification is supposed to do, so I have not had much success in attempting to debug it... if had to guess something with binding variables but I'm honestly not too sure

Regardless, is ACT no longer supported?

**Comment by giltho** [comment]
Hello,

Sorry about the answer delay.
ACT hasn't been tested and used for quite a while, it is indeed broken right now.
I'm currently working on a [revamp of the C memory model](https://github.com/giltho/Kanillian/kanillian) based on CBMC as a frontend, and will try to fix bi-abduction there.
I hope to be able to merge all these changes soon

May I ask your use case? I'd be happy to help if I can :)

**Comment by 2over12** [comment]
Gotcha, I was more experimenting and trying to work through things and see what is available. I am not sure bi-abduction is the right tool for us regardless. I'm working on some SL specification development for a C library and was trying to think of some ways to reduce the burden on the user in writing specifications of these libraries to prove properties in the client ie. specifications we provide may not capture what you need to prove a given client property. The best I have right now as a solution is: have a human in the loop who goes writes and proves a speciation that talks about things the library client needs to reason about, potentially by extending the specifications we already provide. I  think a lot of these properties are going to be context specific and non local though so I don't think bi-abduction is really the right tool here (assuming there even is a reasonable tool for automating this in any respect).

I still think ACT is interesting regardless :), but probably not helpful for the specific use-case here

**Comment by giltho** [comment]
Interesting! Yes, I don't think Bi-abduction will help with any of that.
Because it's automatic, it can't really infer any _intent_ of the developer. It can only do some basic shape analysis.

In general, functional specification synthesis is extremely hard, and human-in-the-loop is still the best solution you'll find

**Comment by 2over12** [comment]
Yeah I had hoped that maybe with user specifications of the client code, bi-abduction might be able to help infer some of the more boring shape properties that might be missing from the library spec for those client specs to hold, while relying on the user for the rest, but I don't think this would actually be useful or possible.
