### ISSUE TITLE
Lifting `free` statement to WISL

### ISSUE THREAD

**Issue by NatKarmios** [GillianPlatform/Gillian#125]
Since `free` is compiled to an if-else that checks the pointer's validity, the current restriction on a branch command and its successor having the same origin ID becomes prohibitive.

Perhaps we could introduce a custom branching mechanism to the TL modules? For example, the `free` command in WISL could either succeed or fail its pointer check, and we could reflect this with a cusom branch case.

**Comment by NatKarmios** [comment]
This will be incorporated into #130.

**Comment by giltho** [comment]
I'd rather we close issues when corresponding PRs are accepted and merged
