### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by NatKarmios** [GillianPlatform/Gillian#165]
We have a lot of branches that haven't been touched in months, years even :P 
It'd be nice to take 10 mins and clear up any we don't need.

**Comment by giltho** [comment]
![image](https://user-images.githubusercontent.com/8451179/200588960-fc7f7227-128c-4eb3-896d-0817c40e3b7a.png)

**Comment by giltho** [comment]
Joke aside, there's a bunch of stuff there that are maybe interesting hahaha
Like the `z3-seq` branch is an interesting to have around just in case. And but yeah I should probably try pruning a bit

**Comment by NatKarmios** [comment]
Done.
