### ISSUE TITLE
Match the theory: the engine should allow branching with error and successes

### ISSUE THREAD

**Issue by giltho** [GillianPlatform/Gillian#182]
Right now, Gillian doesn't allow for branching when there are both Successes and Error cases
For example, take the "core predicate" called `is_true` which takes a boolean. It's setter does nothing if the boolean is true, and fails if it's false. (This is a tiny model, but a similar behaviour happens in CHERI-C-Gillian when checking pointer tags.

Producing this assertion may or may not fail, depending on the order of production.
```
<is_true>(b) * (b == true)
```

In theory, producing <is_true> should branch in two cases and the `success` with pc `b==true` and the 'error' with pc `b==false`, and the latter should vanish when producing `b==true`

**Comment by NatKarmios** [comment]
#246
