### ISSUE TITLE
Documentation links don't work

### ISSUE THREAD

**Issue by NicolasArmero** [GillianPlatform/Gillian#208]
Hello, I'm a grad student that is looking for a tool to do SE testing in some javascript applications, unfortunately none of the links for the documentation work.
I thought I should tell you in case you didn't notice.

To make the most of this issue I also wanted to ask if your tool has support for .js files designed to be loaded in web browsers or it just run with node runtime by default.

Thank you,
Nicolás Armero Baigorri

**Comment by NatKarmios** [comment]
Hi Nicolás,

Can you specify where you're looking at the documentation? I just had a check at https://GillianPlatform.github.io and it seems to be working fine.

In terms of JS, I'm reasonably sure Gillian can verify JavaScript regardless of what environment you intend to run it in, however I'm not sure that it supports the full suite of web APIs (@giltho should be able to answer this better).
Also bear in mind that JS is currently broken in Gillian (#113) 😛 Though it's currently my priority to get it fixed, so hopefully that'll be done soon.

**Comment by NatKarmios** [comment]
Ah, I see, the links in the README haven't been updated - thanks for letting me know 🙂
