### ISSUE TITLE
Website does not work

### ISSUE THREAD

**Issue by glor** [GillianPlatform/Gillian#307]
When I visit https://gillianplatform.github.io/sphinx/index.html (which https://gillianplatform.github.io/ redirects to), I get an error that the file could not be found.

**Comment by NatKarmios** [comment]
Whoops, sorry about that. I'll look into it now.

**Comment by NatKarmios** [comment]
Ah, `make` wasn't building sphinx because the sphix directory already exists. Just fixed it.
