### ISSUE TITLE
Gillian-JS is still labeled with broken in sphinx documentation.

### ISSUE THREAD

**Issue by bjrjk** [GillianPlatform/Gillian#311]
Via viewing the PR #229 , I believed that Gillian-JS project has been fixed but in documentation it is still unfixed at https://gillianplatform.github.io/sphinx/js/index.html.

**Comment by giltho** [comment]
Right, so it's mostly fixed, but is known to still have unresolved quirks which will make it crash, or could even result in some unsoundnesses. Until we're sure and it's battle tested, we won't mark it as fully fixed

**Comment by bjrjk** [comment]
Thanks a lot!
