### ISSUE TITLE
34 seconds for symbolic execution, one file, 2 assertions, on modern CPU

### ISSUE THREAD

**Issue by klausnat** [GillianPlatform/Gillian#315]
Hello,

Symbolic testing for the file arrays1.js form Buckets is taking 34 seconds

dune exec -- gillian-js wpst Examples/Cosette/Buckets/arrays/arrays1.js

is this normal or is it too long? What might be the reason?

![34_seconds](https://github.com/user-attachments/assets/26405c04-b4bf-430d-b874-5943f30e5325)

I checked memory during the process, and it was enough memory... 

![изображение](https://github.com/user-attachments/assets/179510ab-9dfe-4edf-8b98-217b8d8d136d)

Thank you.

**Comment by giltho** [comment]
Yes, you need `-l disabled` as an argument to disabled the production of `file.log` which takes most of the execution time

**Comment by klausnat** [comment]
OH! Thanks, it worked.
