### ISSUE TITLE
Integrate Core-JS

### ISSUE THREAD

**Issue by indo-dev-0** [GillianPlatform/Gillian#71]
JS-2-GIL supports [almost](https://gillianplatform.github.io/docs/js/js-2-gil/) the entire ES5 standard library, I assume because those functions are typically implemented in C++ and require manual translation from specs to JSIL.

However, [core-js](https://github.com/zloirock/core-js) provides polyfills for a large number of APIs. This would add a level of indirection (informal spec -> JS -> JSIL) but would be no less secure than relying on the C++ implementation.  This could expand the number of passing Test262 subtests by [up to ~1,200](https://gillianplatform.github.io/docs/js/js-2-gil/#explanation-table-rows).

**Comment by giltho** [comment]
Internal libraries of JS are currently implemented in JSIL directly. We could add a JS library that does it for us, but we are currently still at a quite theoretical place and the real-world code we verified in the past never used these libraries.

That being said, core-js would definitely be an option :)

**Comment by NatKarmios** [comment]
This isn't a particular priority; closing for the time being.
