### ISSUE TITLE
Assert not triggered

### ISSUE THREAD

**Issue by bobismijnnaam** [GillianPlatform/Gillian#73]
I ran into the following program today:

```
function yy() {
    try {
        while (true) {
            try {
                return -1;
            } finally {
                throw -1;
            }
        }
    } catch (err) {
        Assert(false);
        console.log("catch")
    }
}
```

In firefox it prints "catch" (of course after first removing the `Assert` call), but Gillian-JS does not fail on the Assert, but reports that the snippet passes. Is this a bug or am I misinterpreting javascript control flow? I used the online Gillian-JS editor for testing this snippet.

**Comment by giltho** [comment]
Is this the whole program you ran ?
If so, it is missing the function call, otherwise, the function is defined but never executed.

The correct program to run to raise an error would be :
```js
function yy() {
    try {
        while (true) {
            try {
                return -1;
            } finally {
                throw -1;
            }
        }
    } catch (err) {
        Assert(false);
        console.log("catch")
    }
}
yy()
```

**Comment by bobismijnnaam** [comment]
I see, if I put the function call after it I can reproduce it reliably in the online gillian environment.

It does happen sometimes that the online environment first says "ANALYSIS WAS NOT SUCCESFUL", but if I then add a space somewhere in the snippet it runs again and then verifies...

After a while the following program stopped verifying:

```javascript
function zz(v) {
    a: while (true) {
        b: while (true) {    
            break b;
        }     
        break a;
    } 
}
zz(1);
```

But maybe I overloaded the server? Since the dead code detection highlighting seemed to work properly still (i.e. if I remove one of the breaks the whole function is shaded). Also the initial example that loads does not verify for me anymore so I might have triggered a bug on the server side...

In any case, the original issue is solved for me and seems to be functioning fine, so I'm closing this.
